# Default values for trident
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ExternalSecret Configuration
secretStoreRef:
  name: vault-backend
  kind: ClusterSecretStore

# Maps to $gitroot/values-secret.yaml-template declaration
tridentFSX:
  iscsi:
    key: secret/data/global/fsx-admin
    secretName: trident-ontap-iscsi-svm
    storagePrefix: trident_iscsi
    lunsPerFlexvol: 100
    mgmtLIF: ""
    storageDriverName: ontap-san
    svm: fsx
  storageClass:
    name: trident-csi-iscsi
    backendType: ontap-san
    fsType: ext4
