apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-trident-iscsi-svm2
  namespace: trident
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
{{- with .Values.tridentFSX }}
  target:
    name: {{ .iscsi.secretName }}2
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .iscsi.key }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .iscsi.key }}
        content: true
{{- end }}
